import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";

type AboutModalProps = {
  show: boolean;
  onHide: () => void;
};

const AboutModal = ({ show, onHide }: AboutModalProps) => (
  <Modal show={show} onHide={onHide} centered size="xl">
    <Modal.Header closeButton>
      <Modal.Title>About eCruziDB</Modal.Title>
    </Modal.Header>
    <Modal.Body>
      <div style={{ paddingLeft: "2em", paddingRight: "2em", justifyContent: "justify", textAlign: "justify" }}>
        <p>
          The <i>Trypanosoma cruzi</i> is the causative agent of Chagas Disease, which is a Neglected Tropical Disease. The World Health Organization (WHO) estimates that more than 7 million people are infected with <i>T. cruzi</i>, the vast majority living in Latin America. Chagas disease is entirely curable when detected at an early stage. However, without diagnosis and treatment during the acute phase, the disease progresses to a chronic stage, and approximately 30% of chronically infected individuals develop cardiac complications, while one in 10 develop digestive or neurological complications, or a combination of both. It is estimated that Chagas disease causes more than 10,000 deaths annually (<a href="https://www.who.int/news-room/fact-sheets/detail/chagas-disease-(american-trypanosomiasis)" target="_blank" rel="noopener noreferrer">WHO</a>). 
        </p>
        <p>        
          The <a href={import.meta.env.BASE_URL} target="_blank" rel="noopener noreferrer">eCruziDB</a> database contains more than 7,000 <i>Trypanosoma cruzi</i> epitopes generated by genome Phage Display (gPhage). This particular dataset is derived from interactions with antibodies of patients infected with <i>T. cruzi</i> at different stages of Chagas disease, described in <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC8185243/" target="_blank" rel="noopener noreferrer">Teixeira et al. (2021)</a>. gPhage unbiased libraries of the eukaryotic parasite <i>T. cruzi</i> enabled the identification of thousands of antigens recognized by serum samples from patients with Chagas disease. Because most of these antigens are hypothetical proteins, gPhage provides evidence of their expression during infection and a novel repertoire of proteins to be studied and evaluated for their potential role in Chagas disease and theranostic development (i.e., vaccine). The database we built is the most comprehensive map of Chagas disease antibody response, including linear and putative conformation epitopes, many rich in repetitive elements, which allow the parasite to evade a buildup of neutralizing antibodies directed against protein domains that mediate infection pathogenesis. 
        </p>
        <p>
          eCruziDB allows a range of epitope browsing functions: search for specific epitope sequences, find other peptides sharing the same epitope, and explore the <i>T. cruzi</i> genomic regions potentially encoding these epitopes. The <i>T. cruzi</i> genome is known for its highly repetitive nature and large protein families. Therefore, being able to navigate the genomic regions associated with each epitope is particularly useful. Users can download all epitopes, along with the peptides used for their identification and the corresponding DNA inserts that encode them.
        </p>
      </div>
    </Modal.Body>
    <Modal.Footer>
      <Button variant="secondary" onClick={onHide}>
        Close
      </Button>
    </Modal.Footer>
  </Modal>
);

export default AboutModal;